// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce_api.Data;

#nullable disable

namespace ecommerce_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009070218_AddProductStock")]
    partial class AddProductStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("ecommerce_api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ecommerce_api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Clothing for men",
                            Name = "men's clothing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jewelry and accessories",
                            Name = "jewelery"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Electronic devices and gadgets",
                            Name = "electronics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Clothing for women",
                            Name = "women's clothing"
                        });
                });

            modelBuilder.Entity("ecommerce_api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ecommerce_api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ecommerce_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9191),
                            Description = "Your perfect pack for everyday use and walks in the forest. Sturdy 12oz fabric, double-sided cover and stitched flap and detail.",
                            ImageUrl = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
                            Price = 109.95m,
                            Rating = 3.8999999999999999,
                            RatingCount = 120,
                            Stock = 10,
                            Title = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9194),
                            Description = "Slim-fitting style, contrast raglan sleeve set-in sleeve for freedom of movement and casual comfort.",
                            ImageUrl = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
                            Price = 22.3m,
                            Rating = 4.0999999999999996,
                            RatingCount = 259,
                            Stock = 10,
                            Title = "Mens Casual Premium Slim Fit T-Shirts",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9197),
                            Description = "Great outerwear jackets for spring/autumn/winter, suitable for many occasions.",
                            ImageUrl = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
                            Price = 55.99m,
                            Rating = 4.7000000000000002,
                            RatingCount = 500,
                            Stock = 10,
                            Title = "Mens Cotton Jacket",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9199),
                            Description = "Inspired by the mythical water dragon that protects the ocean's pearl.",
                            ImageUrl = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
                            Price = 695.0m,
                            Rating = 4.5999999999999996,
                            RatingCount = 400,
                            Stock = 10,
                            Title = "John Hardy Women's Gold & Silver Dragon Bracelet",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9201),
                            Description = "USB 3.0 and USB 2.0 compatible, fast data transfers, improve PC performance.",
                            ImageUrl = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
                            Price = 64.0m,
                            Rating = 3.2999999999999998,
                            RatingCount = 203,
                            Stock = 10,
                            Title = "WD 2TB Elements Portable External Hard Drive",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9204),
                            Description = "Expand your PS4 gaming experience, play games fast with this compact and soft external hard drive.",
                            ImageUrl = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
                            Price = 114.0m,
                            Rating = 4.7999999999999998,
                            RatingCount = 400,
                            Stock = 10,
                            Title = "WD 4TB Gaming Drive Works with Xbox",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9206),
                            Description = "21.5 inches Full HD (1920 x 1080) IPS ultra-thin monitor, 4ms response time, widescreen IPS.",
                            ImageUrl = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
                            Price = 599.0m,
                            Rating = 2.8999999999999999,
                            RatingCount = 250,
                            Stock = 10,
                            Title = "Acer SB220Q bi 21.5 Full HD Monitor",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9208),
                            Description = "Super ultrawide view, 32:9 aspect ratio, 1800R curve for immersive experience.",
                            ImageUrl = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
                            Price = 999.99m,
                            Rating = 2.2000000000000002,
                            RatingCount = 140,
                            Stock = 10,
                            Title = "Samsung 49' Curved LED Gaming Monitor",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9210),
                            Description = "Detachable liner waterproof winter coat, casual warm outwear with hood.",
                            ImageUrl = "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
                            Price = 56.99m,
                            Rating = 2.6000000000000001,
                            RatingCount = 235,
                            Stock = 10,
                            Title = "BIYLACLESEN Women's 3-in-1 Snowboard Jacket",
                            VendorId = 999
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9213),
                            Description = "100% polyurethane, 100% polyester lining, zippered detail, lightweight and comfortable.",
                            ImageUrl = "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
                            Price = 29.95m,
                            Rating = 2.8999999999999999,
                            RatingCount = 340,
                            Stock = 10,
                            Title = "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
                            VendorId = 999
                        });
                });

            modelBuilder.Entity("ecommerce_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            CreatedAt = new DateTime(2026, 10, 9, 7, 2, 18, 126, DateTimeKind.Utc).AddTicks(9248),
                            Email = "admin@store.com",
                            FullName = "Admin",
                            PasswordHash = "$2a$11$LyEKv.tCDMiUNvHt/jd0me0etoZrZ2uPDKJJ40gTBfZAVj9rbCeUa",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("ecommerce_api.Models.VendorApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("VendorApplications");
                });

            modelBuilder.Entity("ecommerce_api.Models.CartItem", b =>
                {
                    b.HasOne("ecommerce_api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce_api.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecommerce_api.Models.Order", b =>
                {
                    b.HasOne("ecommerce_api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecommerce_api.Models.OrderItem", b =>
                {
                    b.HasOne("ecommerce_api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce_api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecommerce_api.Models.Product", b =>
                {
                    b.HasOne("ecommerce_api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce_api.Models.User", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ecommerce_api.Models.VendorApplication", b =>
                {
                    b.HasOne("ecommerce_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecommerce_api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ecommerce_api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ecommerce_api.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
